import React, { useState, useEffect } from 'react';
import { PricingCard } from './LandingPage';

interface PageProps {
  onBack: () => void;
  onNavigate?: (path: string) => void;
}

const PageLayout: React.FC<{ title: string; children: React.ReactNode; onBack?: () => void; wide?: boolean }> = ({ title, children, onBack, wide }) => (
  <div className="min-h-screen bg-[#030014] text-white overflow-y-auto animate-slide-up relative font-['Outfit']">
    {/* Background Effects */}
    <div className="fixed inset-0 z-0 overflow-hidden pointer-events-none">
       <div className="absolute top-[-10%] left-[-10%] w-[50vw] h-[50vw] bg-indigo-600/10 rounded-full blur-[100px]" />
       <div className="absolute inset-0 bg-[url('https://grainy-gradients.vercel.app/noise.svg')] opacity-20 mix-blend-overlay"></div>
    </div>

    <div className={`relative z-10 container mx-auto px-6 py-12 ${wide ? 'max-w-7xl' : 'max-w-4xl'}`}>
      {onBack && (
        <button 
            onClick={onBack} 
            className="group flex items-center text-gray-400 hover:text-white transition mb-8"
        >
            <div className="p-2 rounded-full bg-white/5 group-hover:bg-white/10 mr-3 transition">
                <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" /></svg>
            </div>
            <span className="text-sm font-semibold tracking-wide">BACK</span>
        </button>
      )}

      <div className={`glass-panel p-8 md:p-12 rounded-3xl border border-white/10 ${wide ? 'bg-[#050510]/80' : ''}`}>
        {title && <h1 className="text-4xl md:text-5xl font-bold mb-8 bg-clip-text text-transparent bg-gradient-to-r from-white to-gray-400">{title}</h1>}
        <div className="prose prose-invert prose-lg max-w-none text-gray-300">
            {children}
        </div>
      </div>
    </div>
  </div>
);

export const VerifyPage: React.FC<PageProps> = ({ onNavigate }) => {
    const [status, setStatus] = useState('Checking account status...');
    const [progress, setProgress] = useState(0);

    useEffect(() => {
        const params = new URLSearchParams(window.location.search);
        const tier = params.get('tier') || 'free';
        
        const steps = [
            { pct: 20, msg: `Verifying ${tier.toUpperCase()} eligibility...` },
            { pct: 50, msg: 'Checking billing information...' },
            { pct: 80, msg: 'Allocating TURN relay servers...' },
            { pct: 100, msg: 'Verification Complete!' }
        ];

        let step = 0;
        const interval = setInterval(() => {
            if (step < steps.length) {
                setProgress(steps[step].pct);
                setStatus(steps[step].msg);
                step++;
            } else {
                clearInterval(interval);
                setTimeout(() => {
                    onNavigate?.(`/api_key?verified=true&tier=${tier}`);
                }, 800);
            }
        }, 800);

        return () => clearInterval(interval);
    }, [onNavigate]);

    return (
        <div className="min-h-screen bg-[#030014] flex flex-col items-center justify-center relative font-['Outfit']">
             <div className="absolute inset-0 bg-[url('https://grainy-gradients.vercel.app/noise.svg')] opacity-20 mix-blend-overlay"></div>
             
             <div className="relative z-10 text-center max-w-md w-full p-8">
                 <div className="w-20 h-20 mx-auto mb-8 relative">
                     <div className="absolute inset-0 border-4 border-indigo-900 rounded-full"></div>
                     <div className="absolute inset-0 border-4 border-indigo-500 rounded-full border-t-transparent animate-spin"></div>
                     <div className="absolute inset-0 flex items-center justify-center font-bold text-indigo-400 text-xs">
                         {progress}%
                     </div>
                 </div>
                 
                 <h2 className="text-2xl font-bold text-white mb-2">Please Wait</h2>
                 <p className="text-indigo-300 animate-pulse mb-8 h-6">{status}</p>

                 <div className="h-1 w-full bg-gray-800 rounded-full overflow-hidden">
                     <div 
                        className="h-full bg-gradient-to-r from-indigo-500 to-purple-500 transition-all duration-500 ease-out" 
                        style={{ width: `${progress}%` }}
                     ></div>
                 </div>
             </div>
        </div>
    );
}

export const ApiKeyPage: React.FC<PageProps> = ({ onBack, onNavigate }) => {
    const [generatedKeys, setGeneratedKeys] = useState<{key: string, tier: string, created: string}[]>([]);
    const [selectedTier, setSelectedTier] = useState<'free' | 'pro' | 'elite'>('free');
    const [loading, setLoading] = useState(false);
    const hasAutoGenerated = React.useRef(false);

    // Check for verification redirect
    useEffect(() => {
        const params = new URLSearchParams(window.location.search);
        const verified = params.get('verified') === 'true';
        const tier = params.get('tier');

        if (verified && tier && !hasAutoGenerated.current) {
            hasAutoGenerated.current = true;
            setSelectedTier(tier as any);
            generateKeyInternal(tier as any);
            // Clean URL
            window.history.replaceState({}, '', window.location.pathname);
        }
    }, []);

    const generateKeyInternal = (tier: string) => {
        setLoading(true);
        setTimeout(() => {
            const random = Array.from(crypto.getRandomValues(new Uint8Array(16))).map(b => b.toString(16).padStart(2, '0')).join('').substring(0, 16);
            const prefix = `mv_${tier}_`;
            const newKey = `${prefix}${random}`;
            
            setGeneratedKeys(prev => [{
                key: newKey,
                tier: tier,
                created: new Date().toLocaleDateString()
            }, ...prev]);
            setLoading(false);
        }, 600);
    };

    const handleGenerateClick = () => {
        if (selectedTier !== 'free') {
            onNavigate?.(`/verify?tier=${selectedTier}`);
            return;
        }
        generateKeyInternal(selectedTier);
    };

    const copyToClipboard = (text: string) => {
        navigator.clipboard.writeText(text);
        // Could show toast here
    };

    return (
        <PageLayout title="Developer Console" onBack={onBack} wide={true}>
            <div className="grid grid-cols-1 lg:grid-cols-3 gap-12">
                
                {/* Left Column: Generator */}
                <div className="lg:col-span-2 space-y-8">
                    <section className="bg-[#111] p-8 rounded-2xl border border-white/10 relative overflow-hidden">
                        <div className="relative z-10">
                            <h2 className="text-2xl font-bold text-white mb-2">Create New API Key</h2>
                            <p className="text-gray-400 mb-6 text-sm">Select a tier to generate a key with specific bandwidth and TURN relay capabilities.</p>
                            
                            <div className="grid grid-cols-3 gap-4 mb-8">
                                <button 
                                    onClick={() => setSelectedTier('free')}
                                    className={`p-4 rounded-xl border flex flex-col items-center gap-2 transition-all ${selectedTier === 'free' ? 'bg-white/10 border-indigo-500 text-white shadow-[0_0_20px_rgba(99,102,241,0.3)]' : 'bg-transparent border-white/10 text-gray-500 hover:border-white/30'}`}
                                >
                                    <span className="font-bold">Free</span>
                                    <span className="text-[10px] uppercase tracking-wider">P2P Only</span>
                                </button>
                                <button 
                                    onClick={() => setSelectedTier('pro')}
                                    className={`p-4 rounded-xl border flex flex-col items-center gap-2 transition-all ${selectedTier === 'pro' ? 'bg-white/10 border-indigo-500 text-white shadow-[0_0_20px_rgba(99,102,241,0.3)]' : 'bg-transparent border-white/10 text-gray-500 hover:border-white/30'}`}
                                >
                                    <span className="font-bold">Pro</span>
                                    <span className="text-[10px] uppercase tracking-wider">Standard TURN</span>
                                </button>
                                <button 
                                    onClick={() => setSelectedTier('elite')}
                                    className={`p-4 rounded-xl border flex flex-col items-center gap-2 transition-all ${selectedTier === 'elite' ? 'bg-gradient-to-br from-amber-500/20 to-orange-600/20 border-amber-500 text-amber-200 shadow-[0_0_20px_rgba(245,158,11,0.3)]' : 'bg-transparent border-white/10 text-gray-500 hover:border-white/30'}`}
                                >
                                    <span className="font-bold">Elite</span>
                                    <span className="text-[10px] uppercase tracking-wider">Global Relay</span>
                                </button>
                            </div>

                            <button 
                                onClick={handleGenerateClick} 
                                disabled={loading}
                                className="w-full py-4 bg-white text-black font-bold rounded-xl hover:bg-gray-200 transition active:scale-95 disabled:opacity-50 flex items-center justify-center gap-2"
                            >
                                {loading ? <div className="w-5 h-5 border-2 border-black border-t-transparent rounded-full animate-spin"/> : <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 7a2 2 0 012 2m4 0a6 6 0 01-7.743 5.743L11 17H9v2H7v2H4a1 1 0 01-1-1v-2.586a1 1 0 01.293-.707l5.964-5.964A6 6 0 1121 9z" /></svg>}
                                <span>{selectedTier === 'free' ? 'Generate Secret Key' : `Verify & Generate ${selectedTier} Key`}</span>
                            </button>
                        </div>
                    </section>

                    {/* Key List */}
                    <div className="space-y-4">
                        <h3 className="text-lg font-bold text-gray-300">Active Keys</h3>
                        {generatedKeys.length === 0 && (
                            <div className="text-center py-12 border-2 border-dashed border-white/5 rounded-2xl">
                                <p className="text-gray-500 text-sm">No keys generated yet.</p>
                            </div>
                        )}
                        {generatedKeys.map((k, i) => (
                            <div key={i} className="flex items-center justify-between p-4 bg-[#0a0a0f] border border-white/10 rounded-xl animate-fade-in-up">
                                <div className="flex flex-col">
                                    <div className="flex items-center gap-2 mb-1">
                                        <span className={`w-2 h-2 rounded-full ${k.tier === 'elite' ? 'bg-amber-500' : k.tier === 'pro' ? 'bg-indigo-500' : 'bg-gray-500'}`}></span>
                                        <code className="text-sm font-mono text-white">{k.key}</code>
                                    </div>
                                    <span className="text-xs text-gray-500">Created {k.created} • {k.tier.toUpperCase()} Tier</span>
                                </div>
                                <button onClick={() => copyToClipboard(k.key)} className="p-2 hover:bg-white/10 rounded-lg text-gray-400 hover:text-white transition">
                                    <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 5H6a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2v-1M8 5a2 2 0 002 2h2a2 2 0 002-2M8 5a2 2 0 012-2h2a2 2 0 012 2m0 0h2a2 2 0 012 2v3m2 4H10m0 0l3-3m-3 3l3 3" /></svg>
                                </button>
                            </div>
                        ))}
                    </div>
                </div>

                {/* Right Column: Stats */}
                <div className="lg:col-span-1">
                    <div className="bg-gradient-to-b from-[#1a1a20] to-[#0a0a0f] p-6 rounded-2xl border border-white/10 h-full">
                        <h3 className="text-sm font-bold text-gray-400 uppercase tracking-wider mb-6">Quota Usage</h3>
                        
                        <div className="space-y-6">
                            <div>
                                <div className="flex justify-between text-sm mb-2">
                                    <span className="text-white">Monthly Active Users</span>
                                    <span className="text-indigo-400">1,240 / 10k</span>
                                </div>
                                <div className="h-2 bg-gray-800 rounded-full overflow-hidden">
                                    <div className="h-full bg-indigo-500 w-[12%]"></div>
                                </div>
                            </div>

                            <div>
                                <div className="flex justify-between text-sm mb-2">
                                    <span className="text-white">TURN Bandwidth</span>
                                    <span className="text-indigo-400">45 GB / 100 GB</span>
                                </div>
                                <div className="h-2 bg-gray-800 rounded-full overflow-hidden">
                                    <div className="h-full bg-indigo-500 w-[45%]"></div>
                                </div>
                            </div>

                            <div className="pt-6 border-t border-white/5">
                                <div className="flex items-center gap-3 mb-4">
                                    <div className="p-3 bg-green-500/10 rounded-lg">
                                        <svg className="w-6 h-6 text-green-500" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>
                                    </div>
                                    <div>
                                        <p className="text-sm font-bold text-white">System Status</p>
                                        <p className="text-xs text-green-500">All Systems Operational</p>
                                    </div>
                                </div>
                                <button className="w-full py-2 bg-white/5 hover:bg-white/10 border border-white/5 rounded-lg text-xs font-bold text-gray-300">View Full Health Check</button>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </PageLayout>
    );
};

export const Documentation: React.FC<PageProps> = ({ onBack }) => {
    const [activeSection, setActiveSection] = useState(0);
    const [sdkPlan, setSdkPlan] = useState<'free' | 'pro' | 'elite'>('free');

    const sections = [
        "Introduction & Setup",
        "Authentication",
        "Session Management",
        "Realtime Messaging",
        "Group Management",
        "WebRTC Engine (Core)",
        "Voice & Audio Graph",
        "Video & Screen Share",
        "Events & Webhooks",
        "Troubleshooting & FAQ",
        "React Hooks"
    ];

    return (
        <PageLayout title="MasterVoice SDK Reference" onBack={onBack} wide={true}>
            <div className="grid grid-cols-1 lg:grid-cols-4 gap-12">
                {/* Sidebar Navigation */}
                <div className="lg:col-span-1 border-r border-white/10 pr-6">
                    <h4 className="font-bold text-white mb-6 uppercase text-xs tracking-wider">SDK Modules</h4>
                    <ul className="space-y-1">
                        {sections.map((sec, i) => (
                            <li 
                                key={i} 
                                onClick={() => setActiveSection(i)}
                                className={`cursor-pointer px-4 py-3 rounded-xl text-sm font-medium transition-all ${activeSection === i ? 'bg-indigo-600 text-white shadow-lg shadow-indigo-500/20' : 'text-gray-400 hover:text-white hover:bg-white/5'}`}
                            >
                                {i + 1}. {sec}
                            </li>
                        ))}
                    </ul>
                    
                    <div className="mt-8 p-4 bg-indigo-500/10 rounded-xl border border-indigo-500/20">
                        <p className="text-xs text-indigo-300 font-bold mb-2">LATEST VERSION</p>
                        <p className="text-white font-mono text-sm">v2.2.0-beta</p>
                    </div>
                </div>

                {/* Content Area */}
                <div className="lg:col-span-3 min-h-[600px]">
                    {activeSection === 0 && (
                        <div className="animate-fade-in-up">
                            <h2 className="text-3xl font-bold text-white mb-4">1. Introduction & Setup</h2>
                            <p className="mb-6">The MasterVoice SDK provides a unified interface for Supabase Auth, Realtime database events, and WebRTC media handling. It abstracts the complexity of signaling and ICE negotiation.</p>
                            
                            <h3 className="text-xl font-bold text-white mb-2">Installation</h3>
                            <div className="bg-[#111] p-4 rounded-xl border border-white/10 mb-6 font-mono text-sm text-gray-300">
                                npm install @supabase/supabase-js mastervoice-sdk
                            </div>

                            <h3 className="text-xl font-bold text-white mb-2">Initialization</h3>
                            <pre className="bg-[#111] p-4 rounded-xl border border-white/10 overflow-x-auto text-sm text-gray-300">
{`import { MasterVoice } from 'mastervoice-sdk';

const client = new MasterVoice({
  apiKey: 'mv_pk_test_...',
  supabaseUrl: 'https://xyz.supabase.co',
  supabaseKey: 'eyJ...'
});`}
                            </pre>
                        </div>
                    )}

                    {activeSection === 1 && (
                        <div className="animate-fade-in-up">
                            <h2 className="text-3xl font-bold text-white mb-4">2. Authentication</h2>
                            <p className="mb-6">The SDK wraps Supabase GoTrue to provide session persistence and automatic token refreshing for WebSocket connections.</p>
                            <pre className="bg-[#111] p-4 rounded-xl border border-white/10 overflow-x-auto text-sm text-gray-300">
{`// Sign Up
const { user, error } = await client.auth.signUp({
  email: 'dev@example.com',
  password: 'secure-password'
});

// Sign In
const session = await client.auth.signInWithPassword({
  email: 'dev@example.com',
  password: 'secure-password'
});`}
                            </pre>
                        </div>
                    )}

                    {activeSection === 2 && (
                        <div className="animate-fade-in-up">
                            <h2 className="text-3xl font-bold text-white mb-4">3. Session Management</h2>
                            <p className="mb-6">Manage user presence and connection state.</p>
                            <ul className="list-disc pl-5 space-y-2 mb-6 text-gray-400">
                                <li><strong>Heartbeat:</strong> Automatic ping/pong every 30s.</li>
                                <li><strong>Presence:</strong> Realtime online status synchronization.</li>
                            </ul>
                        </div>
                    )}
                </div>
            </div>
        </PageLayout>
    );
};

export const PrivacyPolicy: React.FC<PageProps> = ({ onBack }) => (
  <PageLayout title="Privacy Policy" onBack={onBack}>
      <p className="mb-4">Effective Date: October 26, 2023</p>
      <h3>1. Introduction</h3>
      <p>Welcome to MasterVoice. We are committed to protecting your privacy and ensuring you have a positive experience on our website and in using our products and services.</p>
      <h3>2. Data Collection</h3>
      <p>We do not collect personal data beyond what is required for authentication (email). All communication is peer-to-peer and encrypted.</p>
  </PageLayout>
);

export const TermsOfService: React.FC<PageProps> = ({ onBack }) => (
  <PageLayout title="Terms of Service" onBack={onBack}>
      <h3>1. Acceptance of Terms</h3>
      <p>By accessing and using MasterVoice, you accept and agree to be bound by the terms and provision of this agreement.</p>
      <h3>2. Use License</h3>
      <p>Permission is granted to temporarily download one copy of the materials (information or software) on MasterVoice's website for personal, non-commercial transitory viewing only.</p>
  </PageLayout>
);

export const ContactSupport: React.FC<PageProps> = ({ onBack }) => (
  <PageLayout title="Contact Support" onBack={onBack}>
      <p className="mb-6">Have questions or need help? Reach out to our team.</p>
      <div className="bg-[#111] p-6 rounded-xl border border-white/10">
          <p className="mb-2"><strong>Email:</strong> support@mastervoice.io</p>
          <p className="mb-2"><strong>Twitter:</strong> @MasterVoiceHQ</p>
          <p><strong>Discord:</strong> discord.gg/mastervoice</p>
      </div>
  </PageLayout>
);

export const NotFoundPage: React.FC<PageProps> = ({ onBack }) => (
  <div className="min-h-screen bg-[#030014] flex flex-col items-center justify-center font-['Outfit'] relative">
      <div className="absolute inset-0 bg-[url('https://grainy-gradients.vercel.app/noise.svg')] opacity-20 mix-blend-overlay"></div>
      <h1 className="text-9xl font-bold text-white/10 relative z-10">404</h1>
      <h2 className="text-2xl text-white font-bold mb-4 relative z-10">Page Not Found</h2>
      <button onClick={onBack} className="px-6 py-3 bg-white/10 hover:bg-white/20 text-white rounded-xl transition relative z-10">Go Back Home</button>
  </div>
);

export const PlansPage: React.FC<PageProps> = ({ onBack, onNavigate }) => {
    return (
        <PageLayout title="Choose Your Plan" onBack={onBack} wide={true}>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
                <PricingCard 
                    title="Free" 
                    price="$0" 
                    features={['P2P Calling', 'Unlimited Messages', 'Standard Quality', 'Community Support']} 
                    cta="Get Started"
                    onAction={() => onNavigate?.('/register')}
                />
                <PricingCard 
                    title="Pro" 
                    price="$9" 
                    features={['TURN Relay (Firewall Bypass)', 'HD Voice & Video', 'Group Calls (up to 10)', 'Priority Support']} 
                    recommended={true}
                    cta="Start Trial"
                    onAction={() => onNavigate?.('/verify?tier=pro')}
                />
                <PricingCard 
                    title="Team" 
                    price="$29" 
                    features={['Global Low Latency Network', '4K Screen Sharing', 'Unlimited Group Size', 'Dedicated Support']} 
                    cta="Contact Sales"
                    onAction={() => onNavigate?.('/contact')}
                />
            </div>
        </PageLayout>
    );
};

export const DevPage: React.FC<PageProps> = ({ onBack, onNavigate }) => (
    <PageLayout title="Developer Tools" onBack={onBack}>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div 
                onClick={() => onNavigate?.('/docs')}
                className="p-6 bg-[#111] border border-white/10 rounded-2xl cursor-pointer hover:bg-[#1a1a20] transition group"
            >
                <h3 className="text-xl font-bold text-white mb-2 group-hover:text-indigo-400">Documentation</h3>
                <p className="text-gray-400 text-sm">Read the full SDK reference and integration guides.</p>
            </div>
            <div 
                onClick={() => onNavigate?.('/api_key')}
                className="p-6 bg-[#111] border border-white/10 rounded-2xl cursor-pointer hover:bg-[#1a1a20] transition group"
            >
                <h3 className="text-xl font-bold text-white mb-2 group-hover:text-indigo-400">API Keys</h3>
                <p className="text-gray-400 text-sm">Manage your secret keys and view usage quotas.</p>
            </div>
        </div>
    </PageLayout>
);